#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
stanley_local_path_node.py

Stanley lateral controller using Local Trajectory/Path (/local_trajectory & /local_path)
with dynamic speed control generated by local path planner.

Subscribes:
  /local_trajectory              (global_path_planner/PlannerTrajectory) — local path with speed profile
  /local_path                    (nav_msgs/Path) — fallback local path
  /localization/kinematic_state  (nav_msgs/Odometry) — vehicle pose + twist

Publishes:
  /cmd                           (morai_msgs/CtrlCmd) — steering + throttle/brake
"""

import math
import numpy as np
import rospy
from nav_msgs.msg import Path, Odometry
from morai_msgs.msg import CtrlCmd
from tf.transformations import euler_from_quaternion
from global_path_planner.msg import PlannerTrajectory


class StanleyLocalPathController:
    # Vehicle geometry (Hyundai Ioniq 5)
    WHEELBASE      = 3.000   # m
    FRONT_OVERHANG = 0.845   # m
    REAR_OVERHANG  = 0.790   # m

    def __init__(self):
        rospy.init_node('stanley_local_path', anonymous=False)

        def get_p(name, default):
            return rospy.get_param(f'~stanley/{name}', rospy.get_param(f'~{name}', default))

        self.k_e           = get_p('k_e',           0.6)   # Reduced to prevent high-speed oscillation
        self.k_v           = get_p('k_v',           1.0)
        self.fallback_speed= get_p('fallback_speed', 6.0)
        self.accel_value   = get_p('accel_value',   0.4)
        self.brake_value   = get_p('brake_value',   0.0)
        self.base_lookahead = get_p('base_lookahead', 3.0) # Position is Rear Axle, so Front Axle is exactly 3.0m ahead!
        self.lookahead_gain = get_p('lookahead_gain', 0.1)  # Dynamic lookahead per m/s to compensate for latency
        self.lookahead_idx = get_p('lookahead_idx', 2)
        self.lateral_offset = get_p('lateral_offset', 0.25)  # Shift path left by 25cm to fix rightward bias
        self.max_steer_deg = get_p('max_steer_deg', 40.0)
        self.control_hz    = get_p('control_hz',    20.0)
        self.max_idx_jump  = get_p('max_idx_jump',  10)

        self.max_steer_rad = math.radians(self.max_steer_deg)

        # State
        self.path:           object = None
        self.odom:           Odometry = None
        self.path_xy:        np.ndarray = None   # (N, 2)
        self.path_yaws:      np.ndarray = None   # (N,)
        self.target_speeds:  np.ndarray = None   # (N,)
        self.closest_idx:    int = 0
        self.path_updated:   bool = False

        # Publishers
        self.cmd_pub = rospy.Publisher('/cmd', CtrlCmd, queue_size=1)

        # Subscribers
        rospy.Subscriber('/local_trajectory', PlannerTrajectory, self.trajectory_callback, queue_size=1)
        rospy.Subscriber('/local_path', Path, self.path_callback, queue_size=1)
        rospy.Subscriber('/localization/kinematic_state', Odometry, self.odom_callback, queue_size=1)

        # Control loop timer
        self.timer = rospy.Timer(rospy.Duration(1.0 / self.control_hz), self.control_loop)

        rospy.loginfo(
            f"[Stanley-LocalPath] Started | Sub: /local_trajectory & /local_path | "
            f"k_e={self.k_e} k_v={self.k_v} max_steer={self.max_steer_deg}°"
        )

    def trajectory_callback(self, msg: PlannerTrajectory):
        if len(msg.waypoints) == 0:
            return
        xs = np.array([wp.position.x for wp in msg.waypoints])
        ys = np.array([wp.position.y for wp in msg.waypoints])
        self.target_speeds = np.array([wp.target_speed for wp in msg.waypoints])
        self.path_yaws = np.array([wp.yaw for wp in msg.waypoints])
        self.path_xy = np.stack([xs, ys], axis=1)
        self.path = msg
        self.closest_idx = 0
        self.path_updated = True

    def path_callback(self, msg: Path):
        if self.target_speeds is not None:
            return  # Prefer local_trajectory with speed profile
        if len(msg.poses) == 0:
            return
        xs = np.array([p.pose.position.x for p in msg.poses])
        ys = np.array([p.pose.position.y for p in msg.poses])
        self.path_xy = np.stack([xs, ys], axis=1)
        self.target_speeds = np.full(len(xs), self.fallback_speed)
        
        # Estimate yaws for Path msg if not provided
        dx = np.diff(xs, append=xs[-1])
        dy = np.diff(ys, append=ys[-1])
        self.path_yaws = np.arctan2(dy, dx)
        
        self.path = msg
        self.closest_idx = 0
        self.path_updated = True

    def odom_callback(self, msg: Odometry):
        self.odom = msg
        self.control_loop(None)

    @staticmethod
    def _normalize_angle(angle: float) -> float:
        while angle >  math.pi: angle -= 2.0 * math.pi
        while angle < -math.pi: angle += 2.0 * math.pi
        return angle

    def _get_pose(self):
        pose = self.odom.pose.pose
        twist = self.odom.twist.twist
        x, y = pose.position.x, pose.position.y
        q = pose.orientation
        _, _, yaw = euler_from_quaternion([q.x, q.y, q.z, q.w])
        speed = math.hypot(twist.linear.x, twist.linear.y)
        return x, y, yaw, speed

    def _find_closest_idx(self, fx: float, fy: float) -> int:
        path = self.path_xy
        if path is None or len(path) == 0:
            return 0
        n = len(path)

        if self.path_updated:
            dists = np.hypot(path[:, 0] - fx, path[:, 1] - fy)
            closest = int(np.argmin(dists))
            self.path_updated = False
            return closest

        start = self.closest_idx
        if start >= n:
            return n - 1

        search_window = max(self.max_idx_jump, 15)
        end = min(start + search_window, n)

        sub = path[start:end]
        dists = np.hypot(sub[:, 0] - fx, sub[:, 1] - fy)
        local_idx = int(np.argmin(dists))
        target_idx = start + local_idx

        if target_idx - self.closest_idx > self.max_idx_jump:
            target_idx = self.closest_idx + self.max_idx_jump

        return target_idx

    def _stanley_steer(self, x: float, y: float, yaw: float, speed: float):
        path = self.path_xy
        if path is None or len(path) == 0:
            return 0.0, 0, self.fallback_speed

        # Dynamic lookahead to compensate for control/actuator latency
        # The faster we go, the further ahead we must project to prevent swinging wide
        dynamic_lookahead = self.base_lookahead + self.lookahead_gain * speed
        fx = x + dynamic_lookahead * math.cos(yaw)
        fy = y + dynamic_lookahead * math.sin(yaw)

        idx = self._find_closest_idx(fx, fy)
        self.closest_idx = idx
        n = len(path)

        # Smooth heading calculation by looking ahead a few points
        heading_idx = min(idx + self.lookahead_idx, n - 1)
        if heading_idx > idx:
            dx = path[heading_idx, 0] - path[idx, 0]
            dy = path[heading_idx, 1] - path[idx, 1]
        else:
            prev_idx = max(idx - 1, 0)
            dx = path[idx, 0] - path[prev_idx, 0]
            dy = path[idx, 1] - path[prev_idx, 1]

        path_yaw = math.atan2(dy, dx)
        heading_error = self._normalize_angle(path_yaw - yaw)

        nearest_x, nearest_y = path[idx, 0], path[idx, 1]
        ex = nearest_x - fx
        ey = nearest_y - fy
        cte = math.cos(path_yaw) * ey - math.sin(path_yaw) * ex
        
        # Apply manual offset to fix steady-state rightward bias
        cte += self.lateral_offset

        cte_term = math.atan2(self.k_e * cte, self.k_v + speed)
        steer = heading_error + cte_term
        steer = max(-self.max_steer_rad, min(self.max_steer_rad, steer))

        target_speed = self.target_speeds[idx] if (self.target_speeds is not None and idx < len(self.target_speeds)) else self.fallback_speed
        return steer, idx, target_speed

    def control_loop(self, event):
        if self.path is None or self.path_xy is None or len(self.path_xy) == 0:
            rospy.logwarn_throttle(5.0, "[Stanley-LocalPath] Waiting for /local_trajectory or /local_path...")
            return
        if self.odom is None:
            rospy.logwarn_throttle(5.0, "[Stanley-LocalPath] Waiting for /localization/kinematic_state...")
            return

        x, y, yaw, speed = self._get_pose()
        n = len(self.path_xy)

        if self.closest_idx >= n - 2:
            rospy.loginfo_throttle(2.0, "[Stanley-LocalPath] Reached end of local path.")
            # Local path is updated continuously by local planner, so don't full stop unless trajectory ends
            
        steer_rad, idx, target_speed = self._stanley_steer(x, y, yaw, speed)

        # Dynamic speed control from local planner
        speed_error = target_speed - speed
        if speed_error > 0:
            # Faster acceleration (Proportional to error, min 0.1)
            accel_gain = self.accel_value if self.accel_value > 0.0 else 0.3
            accel = min(1.0, max(0.1, speed_error * accel_gain))
            brake = 0.0
        else:
            accel = 0.0
            # Smooth braking proportional to speed error
            if target_speed < 0.5:
                brake = 1.0  # Full brake if trying to stop
            else:
                brake = min(0.6, abs(speed_error) * 0.15)

        cmd = CtrlCmd()
        cmd.ctrl_mode = 2        # AutoMode
        cmd.gear      = 4        # Drive
        cmd.cmd_type  = 1        # Throttle/Brake/Steer mode
        cmd.accel     = float(accel)
        cmd.brake     = float(brake)
        cmd.steer     = float(steer_rad)

        self.cmd_pub.publish(cmd)

    def _publish_stop(self):
        cmd = CtrlCmd()
        cmd.ctrl_mode = 2
        cmd.gear      = 4
        cmd.cmd_type  = 1
        cmd.accel     = 0.0
        cmd.brake     = 1.0
        cmd.steer     = 0.0
        self.cmd_pub.publish(cmd)


if __name__ == '__main__':
    try:
        StanleyLocalPathController()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
